name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: batch-pipelines

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DBT_PROFILES_DIR: .github/dbt
      DBT_HOST: postgres
      DBT_PORT: 5432
      DBT_DBNAME: postgres
      DBT_SCHEMA: public
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: batch-pipelines/requirements.txt

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Run full CI pipeline
        run: make ci